### ISSUE TITLE
Segfault when inputting empty password to pfstore

### ISSUE THREAD

**Issue by arlake228** [perfsonar/i2util#1]
_From @arlake228 on March 14, 2015 12:50_

Original [issue 1054](https://code.google.com/p/perfsonar-ps/issues/detail?id=1054) created by arlake228 on 2015-01-26T10:09:54.000Z:

<b>What steps will reproduce the problem?</b>
1. pfstore -n -f test.pfs jdoe
2. Press enter.

<b>What is the expected output? What do you see instead?</b>

Expected empty passphrase to be added to pfs, but get segfault instead.

<b>What version of the product are you using? On what operating system?</b>
1.2-2 on Debian Linux.

<b>Please provide any additional information below.</b>

Commit for tests and fix here:
https://code.google.com/r/rshearma-i2util/source/detail?r=6d472a9c1e88d631d26f5f1508f3edc17699d656&amp;name=readpassphrase-fix
https://code.google.com/r/rshearma-i2util/source/detail?r=92fafb919b30efe15ed0ab601f0b4197ccd6bfeb&amp;name=readpassphrase-fix
https://code.google.com/r/rshearma-i2util/source/detail?r=640af2e20c23ce0e99baa49fdde41a5ab3754358&amp;name=readpassphrase-fix
https://code.google.com/r/rshearma-i2util/source/detail?r=20a0cd54da354289972ce28629d55ab0a55b63ca&amp;name=readpassphrase-fix
https://code.google.com/r/rshearma-i2util/source/detail?r=c29e3e9880c6448e41d8ba959430e7bf7fc8a662&amp;name=readpassphrase-fix
https://code.google.com/r/rshearma-i2util/source/detail?r=7b56c128886fbd1d1a19fc9c27b178570e5f4ce9&amp;name=readpassphrase-fix

_Copied from original issue: perfsonar/project#1052_

**Comment by arlake228** [comment]
Comment [#1](https://code.google.com/p/perfsonar-ps/issues/detail?id=1054#c1) originally posted by arlake228 on 2015-01-27T15:14:48.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#2](https://code.google.com/p/perfsonar-ps/issues/detail?id=1054#c2) originally posted by arlake228 on 2015-01-27T15:15:03.000Z:

&lt;empty&gt;

**Comment by arlake228** [comment]
Comment [#3](https://code.google.com/p/perfsonar-ps/issues/detail?id=1054#c3) originally posted by arlake228 on 2015-01-27T15:15:18.000Z:

&lt;empty&gt;

**Comment by rshearman** [comment]
Any feedback on the changes and the timescales for them being committed into the main i2util repository?

**Comment by rshearman** [comment]
FYI, I've rebased to latest master and moved the code to github. New URL here:
https://github.com/perfsonar/i2util/compare/master...rshearman:readpassphrase-fix
