### ISSUE TITLE
Debian build issues

### ISSUE THREAD

**Issue by arlake228** [perfsonar/i2util#2]
Raul from Debian QA reported the following:

> Hello Aaron,
> 
> I'd like to report two things about i2util which you might want to look into:
> 
> 1.) build warnings
> 
> The Debian Build system found an issue ("implicit-declaration") while building i2util from source:
> 
> overview:
> 
> https://qa.debian.org/bls/packages/i/i2util.html
> 
> details:
> 
> https://buildd.debian.org/status/fetch.php?pkg=i2util&arch=amd64&ver=1.2-2&stamp=1438652827
> 
> explanation:
> 
> https://qa.debian.org/bls/bytag/W-implicit-declaration.html
> 
> I'm no c-programmer so I can't provide a patch, sorry.
> 
> There are other warnings during the build which look like they should be fixed. Please check the complete build log at https://buildd.debian.org/status/fetch.php?pkg=i2util&arch=amd64&ver=1.2-2&stamp=1438652827 (section "Build")
> 
> 2.) manpage patch
> 
> Please have a look at my patch that inserts some missing backslashes in the comment lines of the supplied manpages of i2util:
> 
> https://sources.debian.net/src/i2util/1.2-2/debian/patches/
> 
> Maybe you could add that to the next release of i2util? Would be great to get rid of that patch!
> 
>  Regards,
> 
> Raoul

**Comment by arlake228** [comment]
Antoine, can you or Valentin take a look at this and determine if anything is worth adding to master? I believe you already made some changes related to this in the debian branches.

**Comment by laeti-tia** [comment]
The manpage patch has been integrated into master already: https://github.com/perfsonar/i2util/commit/205adc5
I think I have a fix for the build warning that I just pushed to master, but I cannot replicate the same build as he had.  I'll get in touch with him.
