### ISSUE TITLE
Build Emits Error-Related Warning

### ISSUE THREAD

**Issue by mfeit-internet2** [perfsonar/i2util#3]
Warning during compilation:

```
libI2util.a(mach_dep.o): In function `I2GetSysErrList':
mach_dep.c:104: warning: `sys_errlist' is deprecated; use `strerror' or `strerror_r' instead
mach_dep.c:102: warning: `sys_nerr' is deprecated; use `strerror' or `strerror_r' instead
```

Could probably use `strerror()` to cook up something similar in a more standards-compliant way.

**Comment by bltierney** [comment]
is this fixed?

**Comment by mfeit-internet2** [comment]
It isn't.  Given that it's just a warning and the code produced is still functional, I'd be inclined to bump it into 4.1.  It would be worthwhile to find out what uses it other than BWCTL (OWAMP?) and see what kind of lifespan it will need.

This was opened a week after I started at I2.

**Comment by arlake228** [comment]
Bumping to 4.1, just a compile time warning that's not causing us any problems.

**Comment by laeti-tia** [comment]
Also seen in https://github.com/perfsonar/owamp/pull/16  Probably TWAMP work is a good time to try to solve this.

**Comment by vvidic** [comment]
Please review and merge PR #12 if ok.

**Comment by mfeit-internet2** [comment]
Seems sane to me.  Merged.
