### ISSUE TITLE
Modern autoconf complains of deprecated macros

### ISSUE THREAD

**Issue by sshambar** [perfsonar/i2util#6]
Autoconf has deprecated some of macros in configure.ac and in the config/*.m4 files.

I've updated the macros to the new names (which should work on even quite old autoconf), and also updated configure.ac and Makefile.am so that autoreconf should work without issue.

I'll add a pull request. :)

Thanks,
Scott

**Comment by laeti-tia** [comment]
https://github.com/perfsonar/i2util/pull/7 has been merged.
