### ISSUE TITLE
Link error related to syslog names

### ISSUE THREAD

**Issue by sshambar** [perfsonar/i2util#8]
Defining SYSLOG_NAMES on some ports causes syslog.h to define some global constants (bad style on their part, but how it works).

The problem is easily worked around by defining SYSLOG_NAMES for only one source file.  However, since I2util/utilP.h includes syslog.h, it must be done in the source file before utilP.h in included.

I'll submit a pull request with the fix.

Thanks,
Scott

**Comment by laeti-tia** [comment]
https://github.com/perfsonar/i2util/pull/9 has been merged.
